if(NOT DEFINED MANUMESH_SDK_ROOT OR MANUMESH_SDK_ROOT STREQUAL "")
  message(FATAL_ERROR "必须设置 MANUMESH_SDK_ROOT。")
endif()

set(MANUMESH_INSTALLED_CLI
  "${MANUMESH_SDK_ROOT}/bin/manumesh${MANUMESH_EXECUTABLE_SUFFIX}"
)
if(NOT EXISTS "${MANUMESH_INSTALLED_CLI}")
  message(FATAL_ERROR "在 ${MANUMESH_INSTALLED_CLI} 未找到已安装的 CLI。")
endif()

set(MANUMESH_ISOLATED_PATH "${MANUMESH_SDK_ROOT}/bin")
if(WIN32)
  list(APPEND MANUMESH_ISOLATED_PATH
    "$ENV{SystemRoot}/System32"
    "$ENV{SystemRoot}"
  )
endif()
list(JOIN MANUMESH_ISOLATED_PATH ";" MANUMESH_ISOLATED_PATH_VALUE)

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env
    "PATH=${MANUMESH_ISOLATED_PATH_VALUE}"
    "${MANUMESH_INSTALLED_CLI}" --version
  RESULT_VARIABLE MANUMESH_RUNTIME_RESULT
  OUTPUT_VARIABLE MANUMESH_RUNTIME_OUTPUT
  ERROR_VARIABLE MANUMESH_RUNTIME_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE
)
if(NOT MANUMESH_RUNTIME_RESULT EQUAL 0)
  message(FATAL_ERROR
    "已安装 CLI 在隔离运行时环境中失败，退出码为 "
    "${MANUMESH_RUNTIME_RESULT}. stdout='${MANUMESH_RUNTIME_OUTPUT}' "
    "stderr='${MANUMESH_RUNTIME_ERROR}'"
  )
endif()
if(NOT MANUMESH_RUNTIME_OUTPUT MATCHES "^ManuMesh [0-9]+\\.[0-9]+\\.[0-9]+$")
  message(FATAL_ERROR
    "已安装 CLI 返回了意外的版本字符串：'${MANUMESH_RUNTIME_OUTPUT}'。"
  )
endif()

if(MANUMESH_EXPECT_ONETBB_NOTICES)
  if(NOT DEFINED MANUMESH_ONETBB_NOTICE_DIR OR
     MANUMESH_ONETBB_NOTICE_DIR STREQUAL "")
    message(FATAL_ERROR "未提供 oneTBB notices 目录。")
  endif()
  set(MANUMESH_ONETBB_NOTICE_ROOT
    "${MANUMESH_SDK_ROOT}/${MANUMESH_ONETBB_NOTICE_DIR}"
  )
  foreach(MANUMESH_ONETBB_NOTICE IN ITEMS
      README.md
      LICENSE.txt
      third-party-programs.txt)
    if(NOT EXISTS
       "${MANUMESH_ONETBB_NOTICE_ROOT}/${MANUMESH_ONETBB_NOTICE}")
      message(FATAL_ERROR
        "已安装 SDK 缺少 oneTBB notice："
        "${MANUMESH_ONETBB_NOTICE_ROOT}/${MANUMESH_ONETBB_NOTICE}"
      )
    endif()
  endforeach()
endif()

message(STATUS "已验证隔离的已安装运行时：${MANUMESH_RUNTIME_OUTPUT}")
