if(NOT DEFINED MANUMESH_SDK_ROOT OR MANUMESH_SDK_ROOT STREQUAL "")
  message(FATAL_ERROR "MANUMESH_SDK_ROOT is required.")
endif()

set(MANUMESH_INSTALLED_CLI
  "${MANUMESH_SDK_ROOT}/bin/manumesh${MANUMESH_EXECUTABLE_SUFFIX}"
)
if(NOT EXISTS "${MANUMESH_INSTALLED_CLI}")
  message(FATAL_ERROR "Installed CLI was not found at ${MANUMESH_INSTALLED_CLI}.")
endif()

set(MANUMESH_ISOLATED_PATH "${MANUMESH_SDK_ROOT}/bin")
if(WIN32)
  list(APPEND MANUMESH_ISOLATED_PATH
    "$ENV{SystemRoot}/System32"
    "$ENV{SystemRoot}"
  )
endif()
list(JOIN MANUMESH_ISOLATED_PATH ";" MANUMESH_ISOLATED_PATH_VALUE)

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env
    "PATH=${MANUMESH_ISOLATED_PATH_VALUE}"
    "${MANUMESH_INSTALLED_CLI}" --version
  RESULT_VARIABLE MANUMESH_RUNTIME_RESULT
  OUTPUT_VARIABLE MANUMESH_RUNTIME_OUTPUT
  ERROR_VARIABLE MANUMESH_RUNTIME_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE
)
if(NOT MANUMESH_RUNTIME_RESULT EQUAL 0)
  message(FATAL_ERROR
    "Installed CLI failed in an isolated runtime environment with exit code "
    "${MANUMESH_RUNTIME_RESULT}. stdout='${MANUMESH_RUNTIME_OUTPUT}' "
    "stderr='${MANUMESH_RUNTIME_ERROR}'"
  )
endif()
if(NOT MANUMESH_RUNTIME_OUTPUT MATCHES "^ManuMesh [0-9]+\\.[0-9]+\\.[0-9]+$")
  message(FATAL_ERROR
    "Installed CLI returned an unexpected version string: '${MANUMESH_RUNTIME_OUTPUT}'."
  )
endif()

message(STATUS "Validated isolated installed runtime: ${MANUMESH_RUNTIME_OUTPUT}")
